### ISSUE TITLE
Auto change server Country

### ISSUE THREAD

**Issue by Dojima1489** [z4roc/valstore-mobile#11]
I login as Asia/Sea but after close the app and open it again. It change to random server that I didn't play on

**Comment by z4roc** [comment]
Might be that it accidently logs you into eu because I set it as default region, but it should get your selected region from the SharedPreferences.

I removed the default region setting and rewrote the region check but can't test it because I don't have an asia account.
Will release an updated apk, please report back to me after trying.

**Comment by Dojima1489** [comment]
That's Fix! Thank for yours hard work mate.
