### ISSUE TITLE
The items pricing is not showing up after update

### ISSUE THREAD

**Issue by Panonim** [z4roc/valstore-mobile#12]
![Screenshot_2024-06-04-15-21-20-121_de.zaroc.valstore-edit.jpg](https://github.com/z4roc/valstore-mobile/assets/58903942/7fb33d5c-ade9-438f-9249-bb7b2a5320c3)

Only the kingdom currency don't work under cosmetics section.

**Comment by z4roc** [comment]
Hey there, I already stumbled upon this one, seems like I accidently caused this with the bundle fix, because Riot uses
the currencyId as key in the cost object and I changed it.

```
Cost.fromJson(Map<String, dynamic> json) {
    i85ad13f73d1b51289eb27cd8ee0b5741 =
        json['85ad13f7-3d1b-5128-9eb2-7cd8ee0b5741'] ?? // Valorant Points Currency ID
            json['85ca954a-41f2-ce94-9b45-8ca3dd39a00d']; // Kingdom Credits Currency ID
  }
```

Testing went good with addressing both VP and Kingdom credits like shown, this issue will be addressed and fixed with newest release im figuring out right now
